# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
  app.flickr_api.url: https://api.flickr.com/services/rest/

services:
  app.curl:
    class: AppBundle\Wrapper\Curl
  app.flickr_api:
    class: AppBundle\Wrapper\FlickrApi
    arguments: ['@app.curl', '%app.flickr_api.url%', '%app.flickr_api.user_id%', '%app.flickr_api.api_key%']
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
